#!/usr/bin/env node
'use strict';

// swarm-say — the message channel agents use to coordinate, with two guarantees the raw
// `tmux send-keys` version lacked:
//   1. Membership allowlist: the target must be a live window of the SAME swarm, or the message
//      is refused. An agent can't cross-talk into another swarm or your personal session, even if
//      its prompt tells it to.
//   2. Readiness gate: delivery routes through manage.deliver(), which refuses to type into a
//      trust prompt, a resume picker, a permission menu, or a busy/running pane — so a handoff
//      can't silently land inside a permission dialog (dogfood findings #4 + #5).
//
//   swarm-say <swarm> <window> <message...>
//
// The per-swarm shell wrapper (generated by swarm.js) calls this with its own swarm name baked in,
// so agents only ever type `swarm-say <window> "<msg>"`.

const manage = require('./manage');

function main() {
  const [swarm, window, ...rest] = process.argv.slice(2);
  const text = rest.join(' ');
  if (!swarm || !window || !text) {
    process.stderr.write('usage: swarm-say <swarm> <window> <message>\n');
    process.exit(1);
  }
  const target = manage.sanitize(window);
  // Members of this swarm, from the live registry (not just whatever the caller claims).
  // readonly: every agent message spawns this process, and a read-modify-write here raced the
  // server's poll on the shared registry file — swarm-say only ever needs to READ it.
  const members = manage.listManaged({ readonly: true }).filter((w) => w.swarm === swarm);
  const member = members.find((w) => w.label === target);
  if (!member) {
    const names = members.map((w) => w.label).join(', ') || '(none live)';
    process.stderr.write(`swarm-say: "${target}" is not a live member of swarm "${swarm}" — refusing. Members: ${names}\n`);
    process.exit(2);
  }
  const r = manage.deliver(target, text);
  if (r.ok) {
    process.stdout.write(`✓ ${r.status === 'started' ? target + ' is running it' : 'delivered to ' + target}\n`);
    process.exit(0);
  }
  // Not delivered: the pane wasn't ready (trust/resume/running/busy) or the window is gone. Report
  // honestly so the calling agent knows the handoff did NOT land and can retry or wait.
  process.stderr.write(`swarm-say: not delivered to ${target} — ${r.status}${r.stage ? ' (' + r.stage + ')' : ''}. Try again shortly.\n`);
  process.exit(3);
}

main();
